### ISSUE TITLE
Maintainer Promotion - burelc-amazn

### ISSUE THREAD

**Issue by Ulrick28** [o3de/sig-platform#45]
I would like to nominate burelc-amzn to be promoted from reviewer to maintainer status.

Chris meets all the requirements set out for becoming a maintainer except additional maintainer approval (more details here - https://github.com/o3de/community/blob/main/community-membership.md)

    Has been a Reviewer for 2+ months
    8+ reviewed Pull Requests in the previous 2 months
    200+ lines of code changed across all reviewed Pull Requests
    2+ O3DE Maintainers that support the promotion from Reviewer to Maintainer

Chris has also been instrumental in helping users that are new to git and github, providing feedback on documentation, mechanisms, and guidance. 

I'll look for additional support and can this then please be discussed in the next sig-platforms meeting.

Thanks!

**Comment by burelc-amzn** [comment]
PR 2992 alone satisfies the lines of code changed requirement: +20,255 −21,983

**Comment by amzn-jillich** [comment]
Fully support!

**Comment by moraaar** [comment]
Totally support!

**Comment by lsemp3d** [comment]
I also fully support this nomination!

**Comment by amznestebanpapp** [comment]
I support this

**Comment by jromnoa** [comment]
+1

**Comment by RoddieKieley** [comment]
Per #50 I also voice my agreement, as others have above, in support of @burelc-amzn whose work has been very beneficial for those of us who consume O3DE on Linux.

As there have been no 0 or -1 votes, and it has been pointed out that the requirements have been met, what further actions are required here prior to being able to close out this issue?

**Comment by Ulrick28** [comment]
burelc was promoted to maintainer a month ago. Not sure why this is still on the agenda :) If there is an issue and he does not have permissions, let me know!
