### ISSUE TITLE
Proposed SIG-Platform triage meeting for JAN-14-20

### ISSUE THREAD

**Issue by byrcolin** [o3de/sig-platform#51]
Meeting Details

Date/Time: JAN 14, 2022 @ 16:00 UTC(GMT) / 9:00am PDT / 5:00pm BST
Location: Discord SIG-Platform Voice Room
Moderator: Colin Byrne
Note Taker <Volunteer Needed>

The SIG-Platform Meetings repo contains the history past calls, including a link to the agenda, recording, notes, and resources.
SIG Updates

Meeting Agenda

Triage open sig-platform Issues:  https://github.com/o3de/sig-platform/issues

I will integrate all comments below into the meeting info.

**Comment by RoddieKieley** [comment]
@byrcolin Can we bump this into the future by 30 minutes or 1hr, say either 9:30am PDT or 10:00am PDT? I have a one off conflict at that time.

**Comment by RoddieKieley** [comment]
@byrcolin got my other one bumped 30min so all good.
