### ISSUE TITLE
Suggestion for documenting Ubuntu Support Strategy

### ISSUE THREAD

**Issue by tonybalandiuk** [o3de/sig-platform#58]
During the 22.05.0 release we discovered this issue: https://github.com/o3de/o3de/issues/9502

At the time O3DE was on Version: Ubuntu 20.04.4 LTS

One way this issue could have been resolved was to begin supporting Ubuntu 22.04 LTS since it resolves this issue as it is using [shared-mime-info 2.1-2](https://packages.ubuntu.com/jammy/shared-mime-info)

However, one of the reasons we were supporting 20.04.4 LTS was, in part, due to wanting to remain compatible with ROS2 which was also supporting that version of Ubuntu.

To solve this, I recommend we document our strategy for supported Ubuntu versions, and review those details whenever we need to evaluate whether or not we should update supported versions (like a run book).

Why? During the release and trying to resolve the issue, we could have (accidentally) pursued supporting 22.04 LTS and potentially broken our compatibility with ROS2. (even if it would not have "broken" in this instance, there still exists this risk in the future if we don't have a documented and known/understood strategy).

**Comment by byrcolin** [comment]
@spham-amzn Sig-Platform would like you to leave your comments on this. We think it is a good idea to formalize the inclusion/upgrading of a platform. Then we can formalize the procedure.

**Comment by spham-amzn** [comment]
Supporting compatibility with ROS2 was not part of the reason to continue support for 20.04 LTS. In fact, part of the 22.04 updates included planned work to support the next version of ROS2 (Humble), and the version previous version (Galactic) is marked EOL for support for November 2022. 

I would suggest any plans to update support for Ubuntu should be based on either EOS (End of Support) or EOL (End of life), and follow ubuntu's [release schedule ](https://wiki.ubuntu.com/Releases).  That would mean we should continue to maintain support for 20.04.4 until at least April 2025. 

We should strive to at least support major LTS release going forward as well. In moving forward with future releases, backwards compatibility should be taken into account to the minimum supported version. In the case of the 22.04 update, we had to maintain backwards support for OpenSSL and ROS2 while moving forward to the newer versions, and this will be the case for all system library dependencies for O3DE ( library dependencies that are outside of the 3P Packaging system).

To do this we may need to maintain a list of those dependencies into a matrix against all components, 3P packages, etc that rely on them and make sure those dependencies are tested to ensure backwards compatibility.
