### ISSUE TITLE
Create feedback for the tsc about this sigs roadmap

### ISSUE THREAD

**Issue by byrcolin** [o3de/sig-platform#60]
TSC has requested a short list of short term (1 month out), medium term (6 month out) and longer term (1 year out) of roadmap items. This list of items may mention a soft or hard target for release.
The intent is this could be used to compile a web page to inform about what we are aiming for.

**Comment by byrcolin** [comment]
I will coordinate with what other sigs are thinking about doing and give our feedback for the next tsc

**Comment by byrcolin** [comment]
proposal: longer term: drive Linux editor gui parity with other platforms like windows

**Comment by byrcolin** [comment]
proposal: longer term: drive Linux input polish.

**Comment by RoddieKieley** [comment]
proposal: longer term: There was an original effort started in the [o3de-fedora](github.com/spotrh/o3de-fedora) to begin work on being able to build O3DE from source on Fedora. At the time the engine was relatively new on Linux in general and the hurdles were many. Now grabbing the development branch, building on Fedora using the existing 3rdParty dependency system, and using the engine to build something useful is an everyday occurrence.
 
However we do not yet [build and distribute](https://www.o3de.org/download/#linux) an rpm based release that could be directly installable on Fedora, nor can we be built in a way that would allow us to be included within the Fedora distribution and installable via dnf.

To start having an rpm that would be installable via a [COPR](https://copr.fedorainfracloud.org/coprs/) would be good, moving on to a downloadable rpm perhaps, and then finally as a part of the distribution itself.

**Comment by spham-amzn** [comment]
medium term: Linux aarch64 (ARM64) support

**Comment by byrcolin** [comment]
midterm: Snap packaging
