### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-platform#64]
Hi @byrcolin @RoddieKieley! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by RoddieKieley** [comment]
As a start we began working with the tools as provided by github to help sort issues between backlog, ready to be worked on, and in progress at the [sig platform roadmap](https://github.com/orgs/o3de/projects/20/views/1). That being said a further review of the Proposed RFC as linked above is likely in order to compare requirements vs. what is there atm.

**Comment by vincent6767** [comment]
Thanks for the updates @RoddieKieley Is there any target week to update the SIG platform roadmap based on the RFC here? https://github.com/o3de/sig-release/issues/79

**Comment by vincent6767** [comment]
Hi @byrcolin @RoddieKieley , a friendly reminder to help review by next week as we want every SIG to have a roadmap according to the RFC attached above by February 6th, 2023.

**Comment by vincent6767** [comment]
Hi @byrcolin @RoddieKieley 
I see you have the roadmap setup here: https://github.com/orgs/o3de/projects/20
According to the RFC, we need your help with these
1. To add a kind/roadmap label for the roadmap item. Once it's done 
2. To merge this PR: https://github.com/o3de/sig-platform/pull/63

**Comment by byrcolin** [comment]
done

**Comment by vincent6767** [comment]
Thank you very much, @byrcolin !
