### ISSUE TITLE
Proposed RFC Feature: Build and Pack Android Projects with Visual Interface

### ISSUE THREAD

**Issue by Shirley-yhm** [o3de/sig-platform#67]
### Summary:
Enable users to export or build&pack Android Projects on Windows using a graphical interface instead of command line.

### What is the relevance of this feature?
Users can generate Android projects by scripts in cmd now, which may not be user friendly. **Users need to perform the following steps every time they generate an Android project**:
1. Refer to user manual for instrutions on how to [generate Android projects on windows](https://www.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/).
2. Open the command line tool and set up environment variables.
3. Enter several commands to build the Android project.

To simply this process and improve users' experience, this RFC proposes to add a graphical interface when generate Android projects on Windows.

### Feature design description:
Users can perform the following steps to select which levels to pack, set paths of dependences and export or build&pack an Android project. 
1. Open the pop-up window from corresponding menu: `'File -> Build Settings -> Android'`.
2. Set the default level and choose which levels to pack.
3. Set paths of Android SDK, JDK, Gradle, NDK, and location of the Android project. **Once these properties are set, they will be saved into the registry. Thus users don't need to reset them the next time they build an Android project.**
    - Some attributes will be read from environment variables automatically, like paths of Android SDK and JDK. Users can modify them manually too.
5. Export / Build and Pack /Cancel the Android project
    - Export. Export an Android project in the specified directory.
    - Build and Pack. Export an Android project in the specified directory, and then pack it into an APK in this folder.
All programs will be executed in the background and users won't be aware.

### Technical design description:
TBD

**Comment by byrcolin** [comment]
I believe there is another rfc/issue proposing a build option in the editor. Perhaps a little more explanation on what you are envisioning here. The title says build, the description says build and pack... Do you see this as an editor feature or program manager feature or standalone app? Should deployment be considered? Maybe some comparisons to how other engine do it.

**Comment by Shirley-yhm** [comment]
Sorry that I haven't finished this RFC because we are still optimizing the process recently. The optimization is expected to be finished this week, after which I will add some images to show how it looks like and some comparison with other engines.

- The title should be **Build and Pack**. Users can choose to build and pack the exported project in O3DE or Android Studio. We will only end up generating an APK for them, and deployment is not yet considered.

- You said that there may be another rfc/issue proposing a build option in the editor. Did you mean `Project Settings Tool` in [o3de#10445](https://github.com/o3de/o3de/pull/10445)? If yes, maybe we should combine what I proposed in this RFC with `Project Settings Tool` as I mentioned in [o3de#14548](https://github.com/o3de/o3de/discussions/14548). I'm afraid this work may also require involvement of UI/UX team.

**Comment by lawsonamzn** [comment]
https://github.com/o3de/sig-content/issues/123 is an in progress RFC that proposes that scripts are used to drive this, so that users can customize their scripts and use them.  

If you already have a working prototype or code that would improve the project, of course, that would be completely fine, but perhaps theres a way to combine these 2 RFCs, such that the Visual Interface proposed could invoke a script similar to what issue 123 above is proposing, then we get the best of both worlds - users get a visual interface to interact with, and underneath that, a customizable script is being used to do the work, so that if a studio wants to modify the process to customize it for their project, they do not have to touch C++ Code much?

**Comment by tkothadev** [comment]
To add to what @lawsonamzn mentioned, in https://github.com/o3de/sig-content/issues/123, we are proposing to unify the build and pack terminology into "Project Export".

As part of this too, I would like to suggest that this feature be proposed for the Project Manager, since it already deals with project configuration and build settings. Having to do it from the editor feels disjointed because the user experience is routed through the Project Manager first.

**Comment by Shirley-yhm** [comment]
Good job! So when do you expect to finish this work? I found a PR in https://github.com/aws-lumberyard-dev/o3de/pull/497. Will it be included in 23.05.0 Release?

**Comment by Shirley-yhm** [comment]
Good job! So when do you expect to finish this work? I found a PR in https://github.com/aws-lumberyard-dev/o3de/pull/497. Will it be included in 23.05.0 Release?

**Comment by Jackie9527** [comment]
Some issues related this topic.
[3195](https://github.com/o3de/o3de/issues/3195)/[3197](https://github.com/o3de/o3de/issues/3197)/[3208](https://github.com/o3de/o3de/issues/3208)

**Comment by tkothadev** [comment]
The RFC is still in-flight, so no major changes will be included for release at this time.

**Comment by Shirley-yhm** [comment]
I see. I'll keep an eye on the progress and consider how to combine our work :)

**Comment by byrcolin** [comment]
@Shirley-yhm Any updates on this?

**Comment by byrcolin** [comment]
@Shirley-yhm ping

**Comment by byrcolin** [comment]
No response. Closing issue.

**Comment by Ulrick28** [comment]
This is currently in progress thanks to @tkothadev

**Comment by byrcolin** [comment]
At the request of @Ulrick28 I am reopening this issue and assigning it to @tkothadev

**Comment by byrcolin** [comment]
@tkothadev I set you as the assignee, I'll leave this to you to use or close if you already have another ticket that encompasses this.

**Comment by tkothadev** [comment]
Per https://github.com/o3de/o3de/pull/18166, functionality for building/exporting android projects and having a configuration panel for android settings is already implemented and checked into stabilization. It is simplified to a 1-click button to initiate the export for android, and should address all primary concerns with the current feature set for android (and for any settings that are missing, they can be added to the configuration panel).

The documentation PR https://github.com/o3de/o3de.org/pull/2578 outlines everything that is currently available.

That will be the extent of my contribution however. If further features are required, I think a separate issue would need to be created for that.
