### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by aFinchy** [o3de/sig-platform#69]
Hi SIG Platform Members,

To assist new and existing members, I would like to request that all SIG repositories update their readme files with comprehensive information. Please include any and all details that you think would be helpful.

If you require examples, please refer to the following repositories as references:

https://github.com/o3de/sig-docs-community
https://github.com/o3de/sig-simulation

Thank you for your cooperation in improving our repositories and supporting our community.

**Comment by byrcolin** [comment]
updated
