### ISSUE TITLE
Proposed SIG-Platform meeting agenda for 1/23/2024

### ISSUE THREAD

**Issue by byrcolin** [o3de/sig-platform#72]
Adding Ubuntu 24.04 will be released soon, I think we should officially support it and drop support for 20.04 so that we support the latest and the previous release.

**Comment by byrcolin** [comment]
Done criteria:
* Official support for 20.04 issues will go unsupported. No build nodes.
* Updating documentation for supporting 24.04 and dropping 20.04.
* When the official 24.04 build node goes green this will signal official 24.04 support and the 20.04 build node(s) should be shut down.
* Go through the issues/roadmap and drop 20.04 only issues and add retest notes if release not mentioned.

**Comment by Ulrick28** [comment]
I feel we should give users at least a 90 day heads up before we remove 20.04. This way no one is caught by surprise, causing us to lose trust with O3DE users.
